### ISSUE TITLE
usage with node-sharp

### ISSUE THREAD

**Issue by transitive-bullshit** [stackgl/gl-texture2d#16]
Hello!

I'm trying to load raw pixel data into a texture2d using [node-sharp](https://github.com/lovell/sharp)'s raw data output and am having trouble getting it to work consistently.  The following code works on some images (RGBA in my tests) but fails on others (some RGB images), so I'm guessing I'm doing something wrong with the translation of sharp's raw data output to ndarray/texture2d.

```js
const createTexture = require('gl-texture2d')
const ndarray = require('ndarray')
const sharp = require('sharp')

module.exports = async (gl, filePath) => {
  const {
    data,
    info
  } = await sharp(filePath).raw().toBuffer({ resolveWithObject: true })

  const array = ndarray(data, [
    info.width,
    info.height,
    info.channels
  ], [
    info.channels,
    info.width * info.channels,
    1
  ])

  return createTexture(gl, array)
}
```

If I use the `get-pixels` module (snippet below), everything works fine, but `get-pixels` doesn't have as robust of image support (e.g., webp, random permutations of png/jpg settings that you find online).

```js
const getPixels = require('get-pixels')
const util = require('util')
const getPixelsP = util.promisify(getPixels)

module.exports = async (gl, filePath) => {
  const pixels = await getPixelsP(filePath)
  return createTexture(gl, array)
}
```

I'm wondering if anyone has successfully used `sharp` to load textures into `gl-texture2d` or if I'm doing something obviously wrong with my translation of `sharp`'s raw data output to an `ndarray`.

For reference, this is in Node via [headless-gl](https://github.com/stackgl/headless-gl).

Any help is greatly appreciated -- thanks!

**Comment by transitive-bullshit** [comment]
For anyone else who ends up here, I ended up falling back to converting any unsupported images to jpg or png via ffmpeg (which my project already uses heavily) and then loading the resulting jpg or png via `get-pixels`.

**Comment by transitive-bullshit** [comment]
@lovell have you encountered this before?

**Comment by lovell** [comment]
If you need RGBA output from either RGB or RGBA input using sharp then [ensureAlpha](https://sharp.pixelplumbing.com/en/stable/api-channel/#ensurealpha) should help.

**Comment by transitive-bullshit** [comment]
Thanks @lovell! 😄
