### ISSUE TITLE
Remove dependency on DOM classes

### ISSUE THREAD

**Issue by vorg** [stackgl/gl-texture2d#7]
Currently `createTexture2D` checks if provided texture object is some kind of image data by doing following checks

``` javascript
if(obj instanceof HTMLCanvasElement ||
       obj instanceof HTMLImageElement ||
       obj instanceof HTMLVideoElement ||
       obj instanceof ImageData) {
```

that prevents us from suppling valid texture object in non browser environment like [Plask](http://plask.org).

I've run into this issue while trying to use **gl-sprite-text** in [pex](http://vorg.github.io/pex/) and even though i have texture wrapper passing this test:

``` javascript
if(obj.shape && obj.data && obj.stride) {
```

 it breaks because of the DOM classes.

**Comment by mikolalysenko** [comment]
Yeah, this is a good idea.  Maybe another option could be to use Object.toString() or perhaps we could add a test to skip that whole conditional if HTMLCanvasElement etc. are not defined in the current environment?

@hughsk @mattdesl  any ideas?

**Comment by hughsk** [comment]
:+1:

It's not pretty but this would work without changing the existing behaviour at all:

``` javascript
if (('undefined' != typeof HTMLCanvasElement && obj instanceof HTMLCanvasElement) ||
    ('undefined' != typeof HTMLImageElement && obj instanceof HTMLImageElement) ||
    ('undefined' != typeof HTMLVideoElement && obj instanceof HTMLVideoElement) ||
    ('undefined' != typeof ImageData && obj instanceof ImageData)) {
```

**Comment by mattdesl** [comment]
:+1: to @hughsk's solution. 

also @vorg, see my thoughts on text rendering here. Feel free to add any thoughts:
https://github.com/stackgl/contributing/issues/26

**Comment by gre** [comment]
I've provided a PR that implement @hughsk suggested solution.
